// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import { SOUTHBAG_AGENT_MODELS } from "./providers/southbag-agent.models.ts";

export const MODELS = {
	"southbag-agent": SOUTHBAG_AGENT_MODELS,
} as const;
