#!/usr/bin/env node

import { readdirSync, rmSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import type { Model } from "../src/types.ts";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const packageRoot = join(__dirname, "..");

const PROVIDER_ID = "southbag-agent";

const southbagAgentModel: Model<"openai-completions"> = {
	id: "southbag-agent",
	name: "Southbag Agent",
	api: "openai-completions",
	provider: PROVIDER_ID,
	baseUrl: "https://code.southbag.cc/v1",
	compat: {
		supportsStore: false,
		supportsDeveloperRole: false,
		maxTokensField: "max_tokens",
		supportsLongCacheRetention: false,
	},
	reasoning: true,
	input: ["text", "image"],
	cost: {
		input: 0,
		output: 0,
		cacheRead: 0,
		cacheWrite: 0,
	},
	contextWindow: 1_050_000,
	maxTokens: 128_000,
};

const generatedHeader = `// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

`;

function emitModel(model: Model<"openai-completions">, indent: string): string {
	let output = `${indent}"${model.id}": {\n`;
	output += `${indent}\tid: "${model.id}",\n`;
	output += `${indent}\tname: "${model.name}",\n`;
	output += `${indent}\tapi: "${model.api}",\n`;
	output += `${indent}\tprovider: "${model.provider}",\n`;
	output += `${indent}\tbaseUrl: "${model.baseUrl}",\n`;
	output += `${indent}\tcompat: ${JSON.stringify(model.compat)},\n`;
	output += `${indent}\treasoning: ${model.reasoning},\n`;
	output += `${indent}\tinput: ${JSON.stringify(model.input)},\n`;
	output += `${indent}\tcost: {\n`;
	output += `${indent}\t\tinput: ${model.cost.input},\n`;
	output += `${indent}\t\toutput: ${model.cost.output},\n`;
	output += `${indent}\t\tcacheRead: ${model.cost.cacheRead},\n`;
	output += `${indent}\t\tcacheWrite: ${model.cost.cacheWrite},\n`;
	output += `${indent}\t},\n`;
	output += `${indent}\tcontextWindow: ${model.contextWindow},\n`;
	output += `${indent}\tmaxTokens: ${model.maxTokens},\n`;
	output += `${indent}} satisfies Model<"${model.api}">,\n`;
	return output;
}

function generateModels(): void {
	const providersDir = join(packageRoot, "src/providers");

	for (const entry of readdirSync(providersDir)) {
		if (entry.endsWith(".models.ts")) {
			rmSync(join(providersDir, entry));
		}
	}

	let catalog = generatedHeader;
	catalog += `import type { Model } from "../types.ts";\n\n`;
	catalog += `export const SOUTHBAG_AGENT_MODELS = {\n`;
	catalog += emitModel(southbagAgentModel, "\t");
	catalog += `} as const;\n`;
	writeFileSync(join(providersDir, `${PROVIDER_ID}.models.ts`), catalog);

	let aggregator = generatedHeader;
	aggregator += `import { SOUTHBAG_AGENT_MODELS } from "./providers/${PROVIDER_ID}.models.ts";\n\n`;
	aggregator += `export const MODELS = {\n`;
	aggregator += `\t${JSON.stringify(PROVIDER_ID)}: SOUTHBAG_AGENT_MODELS,\n`;
	aggregator += `} as const;\n`;
	writeFileSync(join(packageRoot, "src/models.generated.ts"), aggregator);

	console.log("Generated src/providers/southbag-agent.models.ts");
	console.log("Generated src/models.generated.ts");
}

generateModels();
