#!/usr/bin/env node

import { writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const packageRoot = join(__dirname, "..");

function generateImageModelsFile(): string {
	return `// This file is auto-generated by scripts/generate-image-models.ts
// Do not edit manually - run 'npm run generate-image-models' to update

import type { ImagesApi, ImagesModel } from "./types.ts";

export const IMAGE_MODELS = {
} as const satisfies Record<string, Record<string, ImagesModel<ImagesApi>>>;
`;
}

function main(): void {
	const outputPath = join(packageRoot, "src", "image-models.generated.ts");
	writeFileSync(outputPath, generateImageModelsFile(), "utf-8");
	console.log(`Generated ${outputPath}`);
}

main();
