// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

export const SOUTHBAG_AGENT_MODELS = {
	"southbag-agent": {
		id: "southbag-agent",
		name: "Southbag Agent",
		api: "openai-completions",
		provider: "southbag-agent",
		baseUrl: "https://code.southbag.cc/v1",
		compat: {"supportsStore":false,"supportsDeveloperRole":false,"maxTokensField":"max_tokens","supportsLongCacheRetention":false},
		reasoning: true,
		input: ["text","image"],
		cost: {
			input: 0,
			output: 0,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 1050000,
		maxTokens: 128000,
	} satisfies Model<"openai-completions">,
} as const;
